<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanVerticalSlice.Domain\CleanVerticalSlice.Domain.csproj" />
    <ProjectReference Include="..\CleanVerticalSlice.Application\CleanVerticalSlice.Application.csproj" />
    <ProjectReference Include="..\CleanVerticalSlice.Infrastructure\CleanVerticalSlice.Infrastructure.csproj" />
  </ItemGroup>

</Project>
