<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0-preview.1.25081.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArchTests.Domain\ArchTests.Domain.csproj" />
    <ProjectReference Include="..\ArchTests.Application\ArchTests.Application.csproj" />
  </ItemGroup>
</Project>
